export const lang = {
  EN: {
    translation: {
      login: "Login",
      header: "Expert lawyers, your perfect recourse",
      intro:
        "Dedicated lawyers to protect your rights, strong legal defense every step of the way",
      discover: "Discover dz mouhami",
      language: "EN",
      right: "Work right",
      rates: "Rates",
      sharerating: "Share your rating",
      rate: "Rate",
      clientname: "Client Name",
      fullname: "Full name",
      comment: "Comment",
      send: "Send",
      hire: "Make an appointment",
      choose_time: "Pick the consultation time",
      back: "Back",
      next: "Next",
    },
  },
  FR: {
    translation: {
      login: "Se connecter",
      header: "Avocats experts,votre recours parfait",
      intro:
        "Des avocats dévoués pour protéger vos droits, une défense légale forte à chaque étape",
      discover: "Decouvrir dz mouhami",
      language: "FR",
      right: "Droit de travail",
      rates: "Avis",
      sharerating: "Partager votre avis ",
      rate: "Evaluer",
      clientname: "Nom du client",
      fullname: "Nom complet",
      comment: "Commentaire",
      send: "Envoyer",
      hire: "Prendre un Rendez-vous",
      choose_time: "Choisir le temps de consulation",
      back: "Precedent",
      next: "Suivant",
    },
  },
};
