export const lang = {
  EN: {
    translation: {
      login: "Login",
      header: "Expert lawyers, your perfect recourse",
      intro:
        "Dedicated lawyers to protect your rights, strong legal defense every step of the way",
      discover: "Discover dz mouhami",
      language: "EN",
      right: "Work right",
      rates: "Rates",
      sharerating: "Share your rating",
      rate: "Rate",
      clientname: "Client Name",
      fullname: "Full name",
      comment: "Comment",
      send: "Send",
      hire: "Make an appointment",
      choose_time: "Pick the consultation time",
      back: "Back",
      next: "Next",
      phone: "Phone number",
      appoinement: "Confirm Appointment",
      confirm: "Confirm",
      confirmed: "Your appointment has been successfully confirmed.",
      team: "Our team will contact you soon to confirm more details",
      logout: "Logout",
      manageapp: "Appointment management",
      nameclient: "Name of client",
      number: "Number",
      noapp: "No appoinements for you",
      apphis: "Appointment history",
      addblog: "Add a new blog",
      blogtitle: "Blog title",
      blogsubtitle: "Blog Sub Title",
      blogcontent: "Blog Content",
      myblogs: "My Blogs",
      manageavocats: "Manage Avocats",
      gessite: "Website gestion",
      commenthis: "Cemments history",
      nocom: "No comments",
    },
  },
  FR: {
    translation: {
      login: "Se connecter",
      header: "Avocats experts,votre recours parfait",
      intro:
        "Des avocats dévoués pour protéger vos droits, une défense légale forte à chaque étape",
      discover: "Decouvrir dz mouhami",
      language: "FR",
      right: "Droit de travail",
      rates: "Avis",
      sharerating: "Partager votre avis ",
      rate: "Evaluer",
      clientname: "Nom du client",
      fullname: "Nom complet",
      comment: "Commentaire",
      send: "Envoyer",
      hire: "Prendre un Rendez-vous",
      choose_time: "Choisir le temps de consulation",
      back: "Precedent",
      next: "Suivant",
      phone: "Numéro de téléphone",
      appoinement: "Confirmez le rendez vous",
      confirm: "Confirmer",
      confirmed: "Votre rendez-vous a été confirmé avec succès.",
      team: "Notre équipe vous contactera bientôt pour confirmer plus de détails",
      logout: "Déconnecter",
      manageapp: "Gestion des rendez-vous",
      nameclient: "Nom du client",
      number: "Numéro",
      noapp: "Il y a pas de rendez vous ",
      apphis: "Historique des rendez-vous",
      addblog: "Ajouter un blog",
      blogtitle: "Titre du blog",
      blogsubtitle: "Sous titre du blog",
      blogcontent: "Contenu du blog",
      myblogs: "Mes Blogs",
      manageavocats: "Gestion des avocats",
      gessite: "Gestion du site",
      commenthis: "Historique des commentaires",
      nocom: "Pas de commentaires",
    },
  },
};
